
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Oct 20 20:05:30 CST 2015
//----------------------------------------------------

package net.practice.parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int error = 1;
  public static final int PKG_NAME = 3;
  public static final int INCLUDE = 2;
  public static final int EOF = 0;
}

